### ISSUE TITLE
NameError: name 'defaultdict' is not defined

### ISSUE THREAD

**Issue by urmaspitsi** [jensengroup/xyz2mol#30]
"import xyz2mol" gives following error: "NameError: name 'defaultdict' is not defined"
Am I doing something wrong or did the last commit cause this issue ("Removed defaultdict import")?
(see: https://github.com/jensengroup/xyz2mol/commit/14068eb5deec4143a776bfd43cf615ca8e54a80d)

My use case:
I want to read .xyz file and convert it to rdkit mol file.

best regards,
Urmas

Stack trace: 
-----------------------------------------------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
[<ipython-input-13-424ffef12116>](https://localhost:8080/#) in <module>()
----> 1 import xyz2mol

[/usr/local/lib/python3.7/dist-packages/xyz2mol.py](https://localhost:8080/#) in <module>()
     47 global atomic_valence_electrons
     48 
---> 49 atomic_valence = defaultdict(list)
     50 atomic_valence[1] = [1]
     51 atomic_valence[5] = [3,4]

NameError: name 'defaultdict' is not defined

**Comment by jhjensen2** [comment]
No idea why I allowed that without checking. Anyway, it is undone and should work now

**Comment by urmaspitsi** [comment]
thank you so much! I didn't know that you are THAT FAST! :) I already forked and started to modify myself :)
I prefer to use the official version. Thanks again!

**Comment by urmaspitsi** [comment]
I am still getting the same error. Any idea how can I get it to work?
I am using Google Colab notebook:
(after everything is installed)

import xyz2mol

NameError                                 Traceback (most recent call last)
[<ipython-input-11-424ffef12116>](https://localhost:8080/#) in <module>()
----> 1 import xyz2mol

[/usr/local/lib/python3.7/dist-packages/xyz2mol.py](https://localhost:8080/#) in <module>()
     47 global atomic_valence_electrons
     48 
---> 49 atomic_valence = defaultdict(list)
     50 atomic_valence[1] = [1]
     51 atomic_valence[5] = [3,4]

NameError: name 'defaultdict' is not defined

**Comment by jhjensen2** [comment]
Hmm, works fine for me: https://colab.research.google.com/drive/1xjOETpG8Z0nLQ_BJPjJSStcRrVqcKWkC?usp=sharing

**Comment by urmaspitsi** [comment]
Sorry, my bad! I had to force reinstall with:
!pip install --upgrade --force-reinstall git+https://github.com/jensengroup/xyz2mol

seems to work ok! thanks!
